apiVersion: batch/v1
kind: CronJob
metadata:
  name: registry-cleanup
  namespace: cicd
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: registry:2.8
            command:
            - /bin/sh
            - -c
            - |
              # Delete untagged manifests older than 7 days
              registry garbage-collect --delete-untagged /etc/docker/registry/config.yml
            
            volumeMounts:
            - name: registry-config
              mountPath: /etc/docker/registry
            
            env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          
          volumes:
          - name: registry-config
            configMap:
              name: registry-config
          
          restartPolicy: OnFailure
