apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: cicd
type: Opaque
stringData:
  htpasswd: |
    admin:$2y$05$XjCJl0p5J8H6qZ.nDxF8wOYGj4kPvP6M9HQE0d5fPwJ8qK7lY8K9W
  # Default: admin/admin123 (change in production)