# DAY 3: ArgoCD & GitOps Setup
# Install: kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

---
# ArgoCD Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443

---
# ArgoCD Project for Multi-Environment
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd-platform
  namespace: argocd
spec:
  description: CI/CD Platform Applications
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 'dev'
    server: https://kubernetes.default.svc
  - namespace: 'staging'
    server: https://kubernetes.default.svc
  - namespace: 'prod'
    server: https://kubernetes.default.svc
  - namespace: 'cicd'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: admin
    description: Admin role
    policies:
    - p, proj:cicd-platform:admin, applications, *, */*, allow
    groups:
    - admins
  
  - name: developer
    description: Developer role (read-only prod)
    policies:
    - p, proj:cicd-platform:developer, applications, *, dev/*, allow
    - p, proj:cicd-platform:developer, applications, *, staging/*, allow
    - p, proj:cicd-platform:developer, applications, get, prod/*, allow
    groups:
    - developers

---
# Development Environment Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd-platform
  
  source:
    repoURL: https://github.com/your-org/k8s-manifests
    targetRevision: main
    path: overlays/dev
    
    kustomize:
      namePrefix: dev-
      commonLabels:
        environment: development
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

---
# Staging Environment Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd-platform
  
  source:
    repoURL: https://github.com/your-org/k8s-manifests
    targetRevision: main
    path: overlays/staging
    
    kustomize:
      namePrefix: staging-
      commonLabels:
        environment: staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
    - CreateNamespace=true
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

---
# Production Environment Application (Manual sync)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cicd-notifications
spec:
  project: cicd-platform
  
  source:
    repoURL: https://github.com/your-org/k8s-manifests
    targetRevision: main
    path: overlays/production
    
    kustomize:
      namePrefix: prod-
      commonLabels:
        environment: production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  # Manual sync for production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

---
# ArgoCD Image Updater Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: Docker Registry
      prefix: registry.local:5000
      api_url: http://docker-registry.cicd.svc.cluster.local:5000
      credentials: secret:cicd/registry-auth#htpasswd
      insecure: true
  
  log.level: info

---
# Image Updater for Dev (auto-update latest images)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev-autoupdate
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=registry.local:5000/sample-app
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: cicd-platform
  source:
    repoURL: https://github.com/your-org/k8s-manifests
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# Kustomize Base Structure
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-structure
  namespace: cicd
data:
  base-kustomization.yaml: |
    # base/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    resources:
    - deployment.yaml
    - service.yaml
    - configmap.yaml
    
    configMapGenerator:
    - name: app-config
      literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=base
    
    commonLabels:
      app: sample-app
      managed-by: argocd
  
  dev-kustomization.yaml: |
    # overlays/dev/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: dev
    
    bases:
    - ../../base
    
    namePrefix: dev-
    nameSuffix: -v1
    
    commonLabels:
      environment: dev
    
    replicas:
    - name: sample-app
      count: 2
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      newTag: latest
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - API_ENDPOINT=http://api-dev.local
    
    patchesStrategicMerge:
    - deployment-patch.yaml
    
    patchesJson6902:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: sample-app
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: DEBUG
            value: "true"
  
  staging-kustomization.yaml: |
    # overlays/staging/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: staging
    
    bases:
    - ../../base
    
    namePrefix: staging-
    
    commonLabels:
      environment: staging
    
    replicas:
    - name: sample-app
      count: 3
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      digest: sha256:abc123...  # Specific digest for immutability
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=staging
      - API_ENDPOINT=https://api-staging.example.com
    
    resources:
    - ingress.yaml
    - hpa.yaml
  
  production-kustomization.yaml: |
    # overlays/production/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: prod
    
    bases:
    - ../../base
    
    namePrefix: prod-
    
    commonLabels:
      environment: production
    
    replicas:
    - name: sample-app
      count: 5
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      digest: sha256:def456...  # Immutable production image
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=warn
      - ENVIRONMENT=production
      - API_ENDPOINT=https://api.example.com
    
    resources:
    - ingress.yaml
    - hpa.yaml
    - pdb.yaml
    - networkpolicy.yaml
    
    patchesStrategicMerge:
    - resources-patch.yaml

---
# ArgoCD Notifications Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} is now running version {{.app.status.sync.revision}}.
      {{if eq .app.status.operationState.phase "Succeeded"}}
        Deployment successful! :white_check_mark:
      {{else}}
        Deployment failed! :x:
      {{end}}
  
  template.app-health-degraded: |
    message: |
      Application {{.app.metadata.name}} has degraded health status.
      Details: {{.app.status.conditions}}
  
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-deployed]
  
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "xoxb-your-slack-bot-token"

---
# ApplicationSet for multiple environments
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        replicas: "2"
        autoSync: "true"
      - env: staging
        replicas: "3"
        autoSync: "true"
      - env: prod
        replicas: "5"
        autoSync: "false"
  
  template:
    metadata:
      name: 'app-{{env}}'
    spec:
      project: cicd-platform
      source:
        repoURL: https://github.com/your-org/k8s-manifests
        targetRevision: main
        path: 'overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: '{{autoSync}}'
          selfHeal: '{{autoSync}}'

---
# GitHub Actions workflow to trigger ArgoCD sync
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-sync-workflow
  namespace: cicd
data:
  sync-argocd.yml: |
    name: Sync ArgoCD
    
    on:
      push:
        branches: [ main ]
        paths:
        - 'overlays/**'
    
    jobs:
      sync:
        runs-on: [self-hosted, kubernetes]
        steps:
        - name: Install ArgoCD CLI
          run: |
            curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x /usr/local/bin/argocd
        
        - name: Login to ArgoCD
          run: |
            argocd login argocd-server.argocd.svc.cluster.local:443 \
              --username admin \
              --password ${{ secrets.ARGOCD_PASSWORD }} \
              --insecure
        
        - name: Sync Dev
          if: contains(github.event.head_commit.modified, 'overlays/dev')
          run: |
            argocd app sync app-dev --prune
            argocd app wait app-dev --health
        
        - name: Sync Staging
          if: contains(github.event.head_commit.modified, 'overlays/staging')
          run: |
            argocd app sync app-staging --prune
            argocd app wait app-staging --health
        
        - name: Request Production Sync
          if: contains(github.event.head_commit.modified, 'overlays/production')
          run: |
            echo "Production sync requires manual approval"
            # Create GitHub Issue for approval
            gh issue create \
              --title "Production Deployment Ready" \
              --body "Changes ready for production deployment. Review and approve." \
              --label "deployment,production"