apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
  namespace: cicd
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: williamyeh/wrk:latest
        command:
        - wrk
        - -t12
        - -c400
        - -d30s
        - --latency
        - http://sample-app.dev
        
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
      
      restartPolicy: Never