apiVersion: v1
kind: ConfigMap
metadata:
  name: hpa-test
  namespace: cicd
data:
  test-hpa.sh: |
    #!/bin/bash
    
    # Test HPA behavior under different loads
    
    echo "=== Testing HPA Scaling ==="
    
    # Initial state
    echo "Initial replicas:"
    kubectl get hpa -n dev
    
    # Generate load
    echo "Generating load..."
    kubectl run load-generator \
      --image=busybox \
      --restart=Never \
      -- /bin/sh -c "while true; do wget -q -O- http://sample-app.dev; done"
    
    # Monitor scaling
    for i in {1..20}; do
      echo "=== Minute $i ==="
      kubectl get hpa -n dev
      kubectl top pods -n dev
      sleep 60
    done
    
    # Stop load
    kubectl delete pod load-generator
    
    # Monitor scale down
    echo "=== Monitoring scale down ==="
    for i in {1..10}; do
      echo "Minute $i after load stopped:"
      kubectl get hpa -n dev
      sleep 60
    done
