apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: cicd
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command:
        - k6
        - run
        - --out
        - influxdb=http://influxdb.monitoring:8086/k6
        - /scripts/load-test.js
        
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
      
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      
      restartPolicy: Never