apiVersion: v1
kind: ConfigMap
metadata:
  name: optimize-resources
  namespace: cicd
data:
  analyze.sh: |
    #!/bin/bash
    
    echo "=== Resource Usage Analysis ==="
    
    # Get actual vs requested resources
    kubectl top pods -n dev
    kubectl get pods -n dev -o json | jq -r '
      .items[] | 
      "\(.metadata.name),\(.spec.containers[0].resources.requests.cpu),\(.spec.containers[0].resources.requests.memory)"
    '
    
    # Recommendations
    echo "=== Optimization Recommendations ==="
    kubectl-resource-recommendation -n dev