# DAY 5: Monitoring & Observability
# Prometheus, Grafana, AlertManager, Loki for logs

---
# Install Prometheus Stack via Helm
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring --create-namespace

---
# ServiceMonitor for GitHub Actions Runners
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: github-runners
  namespace: cicd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: github-runner
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# ServiceMonitor for Docker Registry
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: docker-registry
  namespace: cicd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: docker-registry
  endpoints:
  - port: registry
    interval: 30s
    path: /metrics

---
# PrometheusRule for CI/CD Alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cicd-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: cicd.rules
    interval: 30s
    rules:
    
    # High runner queue
    - alert: HighRunnerQueue
      expr: |
        sum(github_runner_queue_length) > 10
      for: 5m
      labels:
        severity: warning
        component: cicd
      annotations:
        summary: "High number of queued GitHub Actions jobs"
        description: "{{ $value }} jobs waiting for runners"
    
    # Runner unavailability
    - alert: RunnerUnavailable
      expr: |
        sum(up{job="github-runner"}) < 2
      for: 5m
      labels:
        severity: critical
        component: cicd
      annotations:
        summary: "Less than 2 runners available"
        description: "Only {{ $value }} runners are up"
    
    # High build failure rate
    - alert: HighBuildFailureRate
      expr: |
        sum(rate(github_actions_workflow_run_conclusion_total{conclusion="failure"}[10m])) /
        sum(rate(github_actions_workflow_run_conclusion_total[10m])) > 0.3
      for: 10m
      labels:
        severity: warning
        component: cicd
      annotations:
        summary: "High build failure rate"
        description: "{{ $value | humanizePercentage }} of builds failing"
    
    # Registry storage filling up
    - alert: RegistryStorageFull
      expr: |
        (kubelet_volume_stats_used_bytes{persistentvolumeclaim="registry-pvc"} / 
         kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="registry-pvc"}) > 0.85
      for: 10m
      labels:
        severity: warning
        component: registry
      annotations:
        summary: "Docker registry storage is filling up"
        description: "Registry is {{ $value | humanizePercentage }} full"
    
    # Deployment failure
    - alert: DeploymentFailed
      expr: |
        kube_deployment_status_replicas_unavailable > 0
      for: 5m
      labels:
        severity: critical
        component: deployment
      annotations:
        summary: "Deployment {{ $labels.deployment }} has unavailable replicas"
        description: "{{ $value }} replicas unavailable in {{ $labels.namespace }}"
    
    # ArgoCD sync failed
    - alert: ArgoSyncFailed
      expr: |
        argocd_app_sync_total{phase="Failed"} > 0
      for: 5m
      labels:
        severity: critical
        component: argocd
      annotations:
        summary: "ArgoCD sync failed for {{ $labels.name }}"
        description: "Application {{ $labels.name }} failed to sync"
    
    # Long build times
    - alert: SlowBuildTimes
      expr: |
        histogram_quantile(0.95, 
          rate(github_actions_workflow_run_duration_seconds_bucket[1h])) > 600
      for: 1h
      labels:
        severity: warning
        component: cicd
      annotations:
        summary: "Build times are slow"
        description: "95th percentile build time is {{ $value }}s"

---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-cicd
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  cicd-dashboard.json: |
    {
      "dashboard": {
        "title": "CI/CD Pipeline Metrics",
        "panels": [
          {
            "title": "Build Success Rate",
            "targets": [
              {
                "expr": "sum(rate(github_actions_workflow_run_conclusion_total{conclusion='success'}[5m])) / sum(rate(github_actions_workflow_run_conclusion_total[5m])) * 100"
              }
            ],
            "type": "stat"
          },
          {
            "title": "Active Runners",
            "targets": [
              {
                "expr": "sum(up{job='github-runner'})"
              }
            ],
            "type": "gauge"
          },
          {
            "title": "Build Duration",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(github_actions_workflow_run_duration_seconds_bucket[5m]))"
              }
            ],
            "type": "graph"
          },
          {
            "title": "Deployment Frequency",
            "targets": [
              {
                "expr": "sum(rate(deployment_succeeded_total[1h]))"
              }
            ],
            "type": "graph"
          },
          {
            "title": "Registry Images",
            "targets": [
              {
                "expr": "count(registry_image_size_bytes)"
              }
            ],
            "type": "stat"
          }
        ]
      }
    }

---
# Prometheus metrics exporter for GitHub Actions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-exporter
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-exporter
  template:
    metadata:
      labels:
        app: github-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: exporter
        image: githubexporter/github-exporter:latest
        ports:
        - containerPort: 9090
          name: metrics
        
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        - name: GITHUB_ORGS
          value: "your-org"
        - name: GITHUB_REPOS
          value: "your-org/your-repo"
        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: github-exporter
  namespace: cicd
  labels:
    app: github-exporter
spec:
  selector:
    app: github-exporter
  ports:
  - port: 9090
    targetPort: 9090
    name: metrics

---
# Loki for log aggregation
# Install: helm install loki grafana/loki-stack -n monitoring

---
# Promtail DaemonSet config for GitHub runners
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: cicd
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki.monitoring:3100/loki/api/v1/push
    
    scrape_configs:
    - job_name: github-runners
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - cicd
      
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      
      pipeline_stages:
      - match:
          selector: '{app="github-runner"}'
          stages:
          - regex:
              expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<message>.*)'
          - labels:
              level:
          - timestamp:
              source: timestamp
              format: RFC3339Nano

---
# AlertManager configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'slack-notifications'
      
      routes:
      - match:
          severity: critical
        receiver: 'slack-critical'
        continue: true
      
      - match:
          severity: warning
        receiver: 'slack-warnings'
      
      - match:
          component: cicd
        receiver: 'cicd-team'
    
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#devops-alerts'
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    
    - name: 'slack-critical'
      slack_configs:
      - channel: '#critical-alerts'
        title: 'CRITICAL: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    
    - name: 'slack-warnings'
      slack_configs:
      - channel: '#warnings'
        title: 'Warning: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    
    - name: 'cicd-team'
      slack_configs:
      - channel: '#cicd-team'
        title: 'CI/CD Alert: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

---
# Custom metrics for deployment tracking
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-metrics
  namespace: cicd
data:
  track-deployment.sh: |
    #!/bin/bash
    
    # Track deployment metrics
    NAMESPACE=$1
    DEPLOYMENT=$2
    
    # Push metrics to Pushgateway
    cat <<EOF | curl --data-binary @- http://prometheus-pushgateway.monitoring:9091/metrics/job/deployment
    # HELP deployment_total Total number of deployments
    # TYPE deployment_total counter
    deployment_total{namespace="${NAMESPACE}",deployment="${DEPLOYMENT}"} 1
    
    # HELP deployment_timestamp Deployment timestamp
    # TYPE deployment_timestamp gauge
    deployment_timestamp{namespace="${NAMESPACE}",deployment="${DEPLOYMENT}"} $(date +%s)
    EOF

---
# GitHub Actions workflow with metrics
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-workflow
  namespace: cicd
data:
  metrics.yml: |
    name: Deployment with Metrics
    
    on:
      push:
        branches: [ main ]
    
    jobs:
      deploy:
        runs-on: [self-hosted, kubernetes]
        steps:
        - name: Deploy
          run: |
            kubectl set image deployment/app app=registry.local:5000/app:${{ github.sha }} -n dev
            kubectl rollout status deployment/app -n dev
        
        - name: Track deployment
          run: |
            # Push custom metrics
            cat <<EOF | curl --data-binary @- http://prometheus-pushgateway.monitoring:9091/metrics/job/github-actions
            deployment_succeeded_total{repo="${{ github.repository }}",env="dev"} 1
            deployment_duration_seconds{repo="${{ github.repository }}",env="dev"} ${{ job.duration }}
            deployment_timestamp{repo="${{ github.repository }}",env="dev"} $(date +%s)
            EOF
        
        - name: Send notification
          if: always()
          run: |
            STATUS="${{ job.status }}"
            curl -X POST https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK \
              -H 'Content-Type: application/json' \
              -d "{
                \"text\": \"Deployment $STATUS for ${{ github.repository }}@${{ github.sha }}\",
                \"blocks\": [{
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Deployment $STATUS*\n• Repo: ${{ github.repository }}\n• Commit: ${{ github.sha }}\n• Environment: dev\"
                  }
                }]
              }"

---
# Jaeger for distributed tracing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui
    port: 16686
    targetPort: 16686
  - name: jaeger-collector
    port: 14268
    targetPort: 14268