apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-cicd
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  cicd-dashboard.json: |
    {
      "dashboard": {
        "title": "CI/CD Pipeline Metrics",
        "panels": [
          {
            "title": "Build Success Rate",
            "targets": [ {
                "expr": "sum(rate(github_actions_workflow_run_conclusion_total{conclusion='success'}[5m])) / sum(rate(github_actions_workflow_run_conclusion_total[5m])) * 100"
              }
            ],
            "type": "stat"
          },

          {
            "title": "Active Runners",
            "targets": [ { "expr": "sum(up{job='github-runner'})" }],
            "type": "gauge"
          },

          {
            "title": "Build Duration",
            "targets": [ { "expr": "histogram_quantile(0.95, rate(github_actions_workflow_run_duration_seconds_bucket[5m]))" }],
            "type": "graph"
          },

          {
            "title": "Deployment Frequency",
            "targets": [ { "expr": "sum(rate(deployment_succeeded_total[1h]))" }],
            "type": "graph"
          },

          {
            "title": "Registry Images",
            "targets": [ { "expr": "count(registry_image_size_bytes)" }],
            "type": "stat"
          }
        ]
      }
    }


