apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd-platform
  namespace: argocd
spec:
  description: CI/CD Platform Applications
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 'dev'
    server: https://kubernetes.default.svc
  - namespace: 'staging'
    server: https://kubernetes.default.svc
  - namespace: 'prod'
    server: https://kubernetes.default.svc
  - namespace: 'cicd'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: admin
    description: Admin role
    policies:
    - p, proj:cicd-platform:admin, applications, *, */*, allow
    groups:
    - admins
  
  - name: developer
    description: Developer role (read-only prod)
    policies:
    - p, proj:cicd-platform:developer, applications, *, dev/*, allow
    - p, proj:cicd-platform:developer, applications, *, staging/*, allow
    - p, proj:cicd-platform:developer, applications, get, prod/*, allow
    groups:
    - developers