apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-structure
  namespace: cicd
data:
  base-kustomization.yaml: |
    # base/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    resources:
    - deployment.yaml
    - service.yaml
    - configmap.yaml
    
    configMapGenerator:
    - name: app-config
      literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=base
    
    commonLabels:
      app: sample-app
      managed-by: argocd
  
  dev-kustomization.yaml: |
    # overlays/dev/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: dev
    
    bases:
    - ../../base
    
    namePrefix: dev-
    nameSuffix: -v1
    
    commonLabels:
      environment: dev
    
    replicas:
    - name: sample-app
      count: 2
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      newTag: latest
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - API_ENDPOINT=http://api-dev.local
    
    patchesStrategicMerge:
    - deployment-patch.yaml
    
    patchesJson6902:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: sample-app
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: DEBUG
            value: "true"
  
  staging-kustomization.yaml: |
    # overlays/staging/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: staging
    
    bases:
    - ../../base
    
    namePrefix: staging-
    
    commonLabels:
      environment: staging
    
    replicas:
    - name: sample-app
      count: 3
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      digest: sha256:abc123...  # Specific digest for immutability
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=staging
      - API_ENDPOINT=https://api-staging.example.com
    
    resources:
    - ingress.yaml
    - hpa.yaml
  
  production-kustomization.yaml: |
    # overlays/production/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: prod
    
    bases:
    - ../../base
    
    namePrefix: prod-
    
    commonLabels:
      environment: production
    
    replicas:
    - name: sample-app
      count: 5
    
    images:
    - name: sample-app
      newName: registry.local:5000/sample-app
      digest: sha256:def456...  # Immutable production image
    
    configMapGenerator:
    - name: app-config
      behavior: merge
      literals:
      - LOG_LEVEL=warn
      - ENVIRONMENT=production
      - API_ENDPOINT=https://api.example.com
    
    resources:
    - ingress.yaml
    - hpa.yaml
    - pdb.yaml
    - networkpolicy.yaml
    
    patchesStrategicMerge:
    - resources-patch.yaml