# Sealed Secrets for GitOps
# Install: kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-guide
  namespace: cicd
data:
  usage.md: |
    # Sealed Secrets Usage
    
    ## Install kubeseal CLI
    ```bash
    wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/kubeseal-0.24.0-linux-amd64.tar.gz
    tar -xvzf kubeseal-0.24.0-linux-amd64.tar.gz
    sudo install -m 755 kubeseal /usr/local/bin/kubeseal
    ```
    
    ## Create sealed secret
    ```bash
    # Create regular secret
    kubectl create secret generic my-secret \
      --from-literal=password=supersecret \
      --dry-run=client -o yaml > secret.yaml
    
    # Seal it
    kubeseal --format yaml < secret.yaml > sealed-secret.yaml
    
    # Commit sealed-secret.yaml to Git (safe to commit!)
    # Apply to cluster
    kubectl apply -f sealed-secret.yaml
    ```

---
# Example Sealed Secret (encrypted)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: cicd
spec:
  encryptedData:
    username: AgCQj8H7k...  # Encrypted value
    password: AgBvR9mN2...  # Encrypted value
  template:
    metadata:
      name: registry-credentials
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
