# service-account.yaml for different namespaces
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  namespace: cicd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: prod