apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache
  namespace: cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard